package commands.Enums;

public enum CommmandType {
    CREATEMEMBER,
    SHOWMEMBERSACTIVITY,
    SHOWALLMEMBERS,
    CREATETEAM,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATEANEWBOARD,
    SHOWALLTEAMBOARDS,
    SHOWBOARDSACTIVITY,
    CREATEBUG,
    CREATESTORY,
    CREATEFEEDBACK,
    //TODO
//    ASSIGNTASKTOAMEMBER
//    CHANGEPRIORITY,
//    CHANGESEVERITY,
//    CHANGESTATUS,
}