package commands.Enums;

public enum CommmandType {
    CREATEMEMBER, //done
    CREATETEAM, //done
    CREATEANEWBOARD, // done
    CREATEBUG, //done
    CREATESTORY, // done
    CREATEFEEDBACK, // done
    ADDMEMBERTOTEAM, // done
    SHOWMEMBERSACTIVITY, // ??
    SHOWALLMEMBERS, // ??
    SHOWALLTEAMS,// done
    SHOWTEAMSACTIVITY, // ??
    SHOWALLMEMBERSTEAM, // done
    SHOWALLTEAMBOARDS, // done
    SHOWBOARDSACTIVITY,
    //TODO
//    ASSIGNTASKTOAMEMBER
//    CHANGEPRIORITY,
//    CHANGESEVERITY,
//    CHANGESTATUS,
}