package commands.Enums;

public enum CommmandType {
    CREATEMEMBER, //done
    CREATETEAM, //done
    CREATEANEWBOARD, // done
    CREATEBUG, //done
    CREATESTORY,
    CREATEFEEDBACK,
    ADDMEMBERTOTEAM,
    SHOWMEMBERSACTIVITY,
    SHOWALLMEMBERS,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITY,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDSACTIVITY,
    //TODO
//    ASSIGNTASKTOAMEMBER
//    CHANGEPRIORITY,
//    CHANGESEVERITY,
//    CHANGESTATUS,
}